---
- hosts: all
  become: yes
  tasks:
    - copy:
        src: /var/lib/jenkins/workspace/health-check-job/check.sh
        dest: /tmp/
    - command: sh /tmp/check.sh
    #- command: sh /tmp/check.sh
     #   delegate_to: 127.0.0.1
