---
- hosts: TOMS_APP,TBAPI,SSP_S1,PROXY_APP
  become: yes
  become_user: "{{ monitoring_user | default('netcrk') }}"
  gather_facts: yes
  tasks:
    - name: "Creates directory {{ monitoring_home }}/td-agent-bit/"
      file:
        path: "{{ monitoring_home }}/td-agent-bit/"
        state: directory
        owner: "{{ monitoring_user }}"
        group: "{{ monitoring_group }}"
        mode: 0775
    - name: Copy fluentbit config files 
      block:
        - name: copy fluentbit toms config file to "{{ monitoring_home }}/td-agent-bit/"
          copy:    
            src: "./../inventory/fluentbit configs/{{inventory_hostname}}.gmsw.netcracker.com/" 
            dest: "{{ monitoring_home }}/td-agent-bit/"
            owner: "{{ monitoring_user }}"
            group: "{{ monitoring_group }}"
            mode: "0644"
            async: 10
            poll: 0
          when: inventory_hostname == "vhtmlweb01bp1-s"
        - name: copy fluentbit toms config file to "{{ monitoring_home }}/td-agent-bit/"
          copy:    
            src: "./../inventory/fluentbit configs/{{inventory_hostname}}.gmsw.netcracker.com/" 
            dest: "{{ monitoring_home }}/td-agent-bit/"
            owner: "{{ monitoring_user }}"
            group: "{{ monitoring_group }}"
            mode: "0644"
            async: 10
            poll: 0
          when: inventory_hostname == "vhtmlweb02bp1-s"
        - name: copy fluentbit toms config file to "{{ monitoring_home }}/td-agent-bit/"
          copy:    
            src: "./../inventory/fluentbit configs/{{inventory_hostname}}.gmsw.netcracker.com/" 
            dest: "{{ monitoring_home }}/td-agent-bit/"
            owner: "{{ monitoring_user }}"
            group: "{{ monitoring_group }}"
            mode: "0644"
            async: 10
            poll: 0
          when: inventory_hostname == "vhtmlweb03bp1-s"
        - name: copy fluentbit toms config file to "{{ monitoring_home }}/td-agent-bit/"
          copy:    
            src: "./../inventory/fluentbit configs/{{inventory_hostname}}.gmsw.netcracker.com/" 
            dest: "{{ monitoring_home }}/td-agent-bit/"
            owner: "{{ monitoring_user }}"
            group: "{{ monitoring_group }}"
            mode: "0644"
            async: 10
            poll: 0
          when: inventory_hostname == "vhtmlweb04bp1-s"
        - name: copy fluentbit tbapi config file to "{{ monitoring_home }}/td-agent-bit/"
          copy:    
            src: "./../inventory/fluentbit configs/{{inventory_hostname}}.gmsw.netcracker.com/" 
            dest: "{{ monitoring_home }}/td-agent-bit/"
            owner: "{{ monitoring_user }}"
            group: "{{ monitoring_group }}"
            mode: "0644"
            async: 10
            poll: 0
          when: inventory_hostname == "vhtmltbp01bp1-s"
        - name: copy fluentbit tbapi config file to "{{ monitoring_home }}/td-agent-bit/"
          copy:    
            src: "./../inventory/fluentbit configs/{{inventory_hostname}}.gmsw.netcracker.com/" 
            dest: "{{ monitoring_home }}/td-agent-bit/"
            owner: "{{ monitoring_user }}"
            group: "{{ monitoring_group }}"
            mode: "0644"
            async: 10
            poll: 0
          when: inventory_hostname == "vhtmltbp02bp1-s"
        - name: copy fluentbit portal config file to "{{ monitoring_home }}/td-agent-bit/"
          copy:    
            src: "./../inventory/fluentbit configs/{{inventory_hostname}}.gmsw.netcracker.com/" 
            dest: "{{ monitoring_home }}/td-agent-bit/"
            owner: "{{ monitoring_user }}"
            group: "{{ monitoring_group }}"
            mode: "0644"
          when: inventory_hostname == "vhtmlprt01bp1-s"
        - name: copy fluentbit portal config file to "{{ monitoring_home }}/td-agent-bit/"
          copy:    
            src: "./../inventory/fluentbit configs/{{inventory_hostname}}.gmsw.netcracker.com/" 
            dest: "{{ monitoring_home }}/td-agent-bit/"
            owner: "{{ monitoring_user }}"
            group: "{{ monitoring_group }}"
            mode: "0644"
          when: inventory_hostname == "vhtmlprt02bp1-s"
        - name: copy fluentbit Proxy API server config file to "{{ monitoring_home }}/td-agent-bit/"
          copy:    
            src: "./../inventory/fluentbit configs/{{inventory_hostname}}.gmsw.netcracker.com/" 
            dest: "{{ monitoring_home }}/td-agent-bit/"
            owner: "{{ monitoring_user }}"
            group: "{{ monitoring_group }}"
            mode: "0644"
          when: inventory_hostname == "vhprxlapi01bp1-s"
        - name: copy fluentbit Proxy API server config file to "{{ monitoring_home }}/td-agent-bit/"
          copy:    
            src: "./../inventory/fluentbit configs/{{inventory_hostname}}.gmsw.netcracker.com/" 
            dest: "{{ monitoring_home }}/td-agent-bit/"
            owner: "{{ monitoring_user }}"
            group: "{{ monitoring_group }}"
            mode: "0644"
          when: inventory_hostname == "vhprxlapi02bp1-s"
        - name: "Restart fluentbit service"
          shell: sudo systemctl restart td-agent-bit
